### ISSUE TITLE
Text Rich Notes

### ISSUE THREAD

**Issue by zacktraczyk** [fercevik729/UCSC-Course-Planner#251] opened 2024-02-13 17:21 UTC
# Text Rich Notes

Add text rich features to notes section of the planner page. Some possible options:

- lists
    - enumerated
    - itemized
    - checklists
- Bold or italic
- Heading options
- Markdown support?

**Comment by fercevik729** [comment] 2024-02-13 21:02
Closed as duplicate of #215

**Closed by fercevik729** 2024-02-13 21:02 UTC
Labels: enhancement, frontend
